### ISSUE TITLE
rebuild-iptables script does not return non-zero exit code on RedHat / CentOs

### ISSUE THREAD

**Issue by iggyzap** [opscode-cookbooks/iptables#20]
Hi,

if iptables rule is incorrect and restarting iptables fails this does not fail chef-client execution, hence potential vulnerability.

Lines of code from rebuild-iptables.erb :
```ruby
def install_redhat(data)
  write_iptables("/etc/sysconfig/iptables", data)
  system("/sbin/service", "iptables", "restart")
end
```

**Comment by juliandunn** [comment]
You might want to report that over here: https://github.com/phlipper/rebuild-iptables
