### ISSUE TITLE
"knife cookbook site install" not working

### ISSUE THREAD

**Issue by salmonte** [opscode-cookbooks/iptables#27]
I tried installing the cookbook using "knife cookbook site install" and I get the following error.

ERROR: IOError: Cannot open or read /home/chef-repo/cookbooks/iptables/metadata.rb!

Also, I noticed a metadata.json gets generated inside the cookbook directory, but no metadata.rb is present.

Any thoughts?

**Comment by bart-lute** [comment]
Hi salmonte,

Not sure if it will work for you but I had the same issue on my Mac. After upgrading the chefdk to the latest version: https://downloads.chef.io/chef-dk/ the cookbook installed, as did several others that were also broken.

Regards,
Bart

**Comment by salmonte** [comment]
Hi Bart,

Thanks for the update. I updated to the latest chef-dk and that worked for
me!


Regards,

Steven Almonte

On Sat, Jan 24, 2015 at 11:59 AM, Bart Lute <notifications@github.com>
wrote:

> Hi salmonte,
>
> Not sure if it will work for you but I had the same issue on my Mac. After
> upgrading the chefdk to the latest version:
> https://downloads.chef.io/chef-dk/ the cookbook installed, as did several
> others that were also broken.
>
> Regards,
> Bart
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opscode-cookbooks/iptables/issues/27#issuecomment-71326945>
> .
>



-- 
Steven Almonte
stevenalmonte@gmail.com
Mobile: (954)266-8240

**Comment by tas50** [comment]
This should be fixed in the 1.0 release, which now includes the metadata file
