### ISSUE TITLE
supermarket version does not have metadata.rb

### ISSUE THREAD

**Issue by mrdimka** [opscode-cookbooks/iptables#29]
I had the following issue which I described in https://github.com/berkshelf/berkshelf/issues/1409 
After checking I noticed that when trying to berks install iptables the supermarket version comes without any metadata.rb file causing berks upload to fail.

**Comment by tas50** [comment]
I'll see if I can get the v1.0 release out tonight

**Comment by tas50** [comment]
1.0 is out.
