### ISSUE TITLE
The README should mention that this cookbook no longer blocks anything by default

### ISSUE THREAD

**Issue by jcnnghm** [opscode-cookbooks/iptables#31]
The major breaking change in https://github.com/opscode-cookbooks/iptables/commit/2dc462cb1ec7e1fe99fda393fc81d8b15ac451f7 really needs to be called out, since it's silent.

**Comment by tas50** [comment]
The 1.0.0 release in the Changelog has a pretty big blurb that this is a breaking change release.  Additionally I bumped the release from .14 to 1.0 to signify this is a major version with breaking changed per semver.

https://github.com/opscode-cookbooks/iptables/blob/master/CHANGELOG.md
